/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meu.projeto.java;

public class App {
    
    public static void main(String[] args) {
        
    String nome = "Isabela"; //Caracteres 
    int idade = 16; // numero sinteiros 
    double altura = 1.60; //booleans
    boolean seiJava = true; // apenas 1 carctere
    char letraInicial = 'I'; 
    
    System.out.println("Nome: " + nome + ", Idade: " + idade + ", Altura: " + altura);

    
    
    // -- Exercicio 1 --
    String time = "Internacional";
       int ano = 1909;
       double socios = 135.500;
       
       System.out.println("O time eh " + time + ", ele foi fundado em " + ano + " e tem " + socios + " socios");
   
       
       
    // -- Exercicio 2 -- 
    int num1 = 15;
    int num2 = 200;
    int soma = num1 + num2;
    
    System.out.println("A soma dos dois numeros = " + soma);
    
    // -- Exercicio 3 --
    int nota1 = 5;
    int nota2 = 8;
    int nota3 = 7;
    int media = (nota1 + nota2 + nota3) / 3;
    
    System.out.println("A media de tres notas = " + media);
    
    // -- Exercicio 4 -- 
    int numero1 = 7;
    int numero2 = 10;
    
    if (numero1 )
    }
}
    
      