/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Classes;

public class App {
    

    public static void main(String[] args) {
       Livro meuLivro = new Livro ("As Aventuras", "Dom Casmurro", 200);
       meuLivro.lancamento();
       Aluno novoAluno = new Aluno ("Isabela", 16566, "TDS");
       novoAluno.boletim();
       Produto novoProduto = new Produto ("bola", 9.90, 20);
       novoProduto.valorTotal();
    }
}
