/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NOVO_Projeto;

public class App {
   
    
    
    public static void main(String[] args) {
         /* String meuNome = "Isabela";
         int minhaIdade;
         minhaIdade = 17;
         double minhaAltura = 1.60;
         boolean jaVintei = false;
         char minhaInicial = 'I';
    
        System.out.println("Meu nome é " + meuNome);
        System.out.println("Minha idade é " + minhaIdade);
        System.out.println("Minha altura é " + minhaAltura);
        System.out.println("Ja fiz vinte anos? " + jaVintei);
        System.out.println("Minha inicial é " + minhaInicial);
    }
         int numero = 5;
         if (numero > 0){
             System.out.println("O numero e positivo");
         } else if (numero < 0) {
             System.out.println("O numero e negativo");
         } else {
             System.out.println("O numero e 0");
             
      int diaDaSemana = 3;
              
switch (diaDaSemana){
    case 1:
        System.out.println("Domingo");
        break;
    case 2:
        System.out.println("Segunda");
        break;
    case 3:
        System.out.println("Terca");
        break;
    case 4:
        System.out.println("Quarta");
        break;
    case 5:
        System.out.println("Quinta");
        break;
    case 6:
        System.out.println("Sexta");
        break;
    case 7:
        System.out.println("Sabado");
        break;
        
}
         
         int num = 4;
         
         String resultado = (num % 2 == 0) ? "Par" : "Impar";
         System.out.println("O numero é " + resultado);*/
         
         
         
         //Atividade 1
         int num = 16;
         String resultado1 = (num >= 0) ? "Par" : "Impar";
         System.out.println("O número é " + resultado1);
      
         
         //Atividade 2
         int idade = 25;
         Boolean resultado2 = (idade >= 18) ? true : false;  
         System.out.println("A idade é maior que 18? " + resultado2);
         
         
         //Atividade 3
         int num1 = 99;
         int num2 = 100;
         int resultado3 = (num1 > num2) ? num1 : num2;
         System.out.println("O maior numero é " + resultado3);
     
         
         //Desafio 
         int ano = 2023;
         String resultado4 = (ano % 4 == 0 && ano % 100 != 0 || ano % 400 == 0) ? "O ano é bissexto" : "O ano não é bissexto";
         System.out.println(resultado4);
            
         
       
         
    }
}
        


